### ISSUE TITLE
[BUG]: Rest call to delete comment returns 404

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [octokit/core.js#634]
### What happened?

I am trying to conditionally delete comments through the following workflow

```yaml
on:
  pull_request:
    types: [ labeled ]


env:
  GH_TOKEN: ${{ github.token }}

jobs:
  clean-atlantis-comments:
    if: contains( github.event.pull_request.labels.*.name, 'atlantis-clean')
    name: clean atlantis and user comments invoking plan
    runs-on: ubuntu-latest

    steps:

      - name: checkout the project
        uses: actions/checkout@v4

      - name: list pull request comments
        shell: bash
        run: |
          gh pr view ${{ github.event.number }} --json comments > comments.json

      - name: delete comments
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const jsonData = JSON.parse(fs.readFileSync('comments.json', 'utf-8'));
            const comments = jsonData.comments;
            for (const cmnt of comments) {
              comment_id = cmnt.id
              if (cmnt.author.login == 'pantelis-karamolegkos' || cmnt.body == 'foo') {
                github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment_id,
                })
              }
            }

```

However this fails with

```
Run actions/github-script@v6
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:6842:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/MyOrg/MyRepo/issues/comments/IC_kwDODse5xs5r3EqV',
    status: 404,
```

### Versions

Using `actions/github-script@v6` which in turn uses `@octokit/core` version: 5.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
